{% set version = "2.0.1" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-rsolnp
  version: {{ version|replace("-", "_") }}

source:
  fn: Rsolnp_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/Rsolnp_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/Rsolnp/Rsolnp_{{ version }}.tar.gz
  sha256: 3b221100abdd1dd5b8d2df9325cc4e28b2ad2a6bd5069594c83f04f331c36792

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
    - r-truncnorm

  run:
    - r-base
    - r-truncnorm

test:
  commands:
    - $R -e "library('Rsolnp')"  # [not win]
    - "\"%R%\" -e \"library('Rsolnp')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=Rsolnp
  license: GPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
  summary: General Non-linear Optimization Using Augmented Lagrange Multiplier Method.
  license_family: GPL

extra:
  recipe-maintainers:
    - conda-forge/r
