{% set version = "2.0.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rsolnp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Rsolnp_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rsolnp/Rsolnp_{{ version }}.tar.gz
  sha256: 3b221100abdd1dd5b8d2df9325cc4e28b2ad2a6bd5069594c83f04f331c36792

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib('c') }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib('m2w64_c') }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-future.apply
    - r-numderiv
    - r-truncnorm
  run:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-future.apply
    - r-numderiv
    - r-truncnorm

test:
  commands:
    - $R -e "library('Rsolnp')"           # [not win]
    - "\"%R%\" -e \"library('Rsolnp')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=Rsolnp
  license: GPL-2.0-only
  summary: General Non-linear Optimization Using Augmented Lagrange Multiplier Method.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
