travis:
  secure:
    BINSTAR_TOKEN: EvhGbZlmMKQ+/gTWAqgK884OKrYOoKoENzxwnxMSM6Yprq+iqINfbLjpo+ZpJycuTtpw9albLKK0ByT2p6FI+xp0mSO9s8ukJ7kt1s/h4UVPrLQFh0D+eq1q3EJI/2LRNw9yGSbiREKlFrJX6xyHBYf0lSql3wz4ahvdxfgcb6Pa3WVXLxb3lsmvM6rmFCJ0EF4hYzZcDA9mWCoMvqdj+WmC0J0zzHFDADTnKfydkJV+k0voNuo0PsDY6xJ5nuExLI0m4jh7hi9QuUyPn93bEgoVya8Mkvnq5dtaUeHFRKafYadbVWtrOKascNvaGVpMojCRktGFp3+keTc/BX6XyRAq3sPBdGn3pBEQEaD7Abryq6gKMSB1ILU1dbnwj4TfIesbYCHwQYxyuZ+LAdCJkq0sT/wJfSDk+zIAscPiDulbUUQ9YAQzGtn/ALV0YQAA760p0ErLILA3lYGb3ZYFAWU7lEUmLp5pVAACIYC11YCrsUrsI1pKO8H69JN/u7LAZjpAVPDJW6MzPoLBBMrOAz+Ud5HISPJpQRlMr5VAbChC9NkPbFdSfhPs8hqWSferiq6rZdyTOsbys83j1DrBO2jK+vFpZkOLzP1oY2yL1Qu27NRRoom8VcaQ8nJ8z/WOJrOldFFWC28WpqF9Uedgu5nEaLOkFNQ+2o771e5BT7o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
