travis:
  secure:
    BINSTAR_TOKEN: h9TRX5+hcDZSH97eDtKGsh+v61beC4BBf1oge1dn92hPmk9aYBeGzHblrpuRN24a/R4yoq8PgHa2AFuBB0X7ZrTuRAkXAuWCdyfqTgC3MR0HxElD/QjcT+RuJijHlS+zl4AqWcM2NSnJspNzZnvKouS3PbjYDZO6LPTaTm4ZDFqMaHV6HNeKJiMSWNcxTGMHm3e0ns/32uPFU0++EJ5S1ea9V3S/+czfT72rgymqFuN1/ZKfte3gMbWJjOJnW/kdcdGT3Bz7mQQsd8OAD74d9y8r8Ptv7Y0WjS9ihFVum+KDwiy56OxncWGsRsH4ROcbfHhgmDdbfNzZdEJZst1Z771m9T268PZHQ7miPbg+HyIhrK9AXmqSHH8FhLCfAN5uSoso/kl57QrZwyDDAmtMKk/Q3BXKvAAzw7itr4Yh98Z0rPMNuqIRKlVIgWmc6bbICUph0WLJzbutsYkW9aN+poW7YRRU/HMkBtHCtRgQ5ddLd0tBs7Zzn1PO2Y8/bW14Yi5EQDJEJ7BVOKOESlHeCCYHPNU09VoOI0mQx7ERzzx+cfw4I0tshiCIpnfT7WZ1k07QgEuQaJ/eQkEq8jzcnKmrwl8I0JpY5UXr4a6cs5e/inbiQiYFMXriNsSuwdmOTFK9LdjS0YVXf4Qd9aj/y1qVVw46/YtwNVgl1fCldsQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
