travis:
  secure:
    BINSTAR_TOKEN: cU0mSJLU8ns3BZlrqD81FIo0WhIC2bJsKLtmpMJjg1V+isMT2n8kBsYPDg7fNkxf/03gIftEB8MECm5PNNo5aHHuy/MQO9xDIWGs70jM4X11POGPEOdUqObUr77lr6NjTyHlTv0Nv49XcdZEAwq9Qa9CvDKsvaHwkp6riDmOWo6pX4/Vav49uZxQIH6gM+/e/av1XXPmNPwCIRo1FlZ+kyL15q2rlZI+HW58HoFhW97GT8YDwoGeF+yzwAOyjYwEmtPCLO18yEBTnFSb+4PzBCg/CrezT4GA2ia/H8Ejk0HpiwhIWOPmUDsqFYezvDnSbYz1ITCwaJojRk8Ii1j2n5deW8ObmRXbhRckGfxSt85pmo0im/r/OSpYyIFoNeMf15PmtIhvpXgkNYUAEr4/flTrJax1Gea/IDKkrpa4m4x9qVOMTop2zBVD2ygrjDkxeFdvsWfji+3gu37v4Yto0OyqsHYLexoKFhIoPanHiqsYdAfKNDJZ8+J7Dueagqzzzlk/EXZHp8ywxHEwO7PeCFt4iQnqkW/PIO1MfHbbdQSRYftY9Hd0+W3hztK7wPJ8n8H+qTd5Jcym1UH4iiWx+GiV6kT4xpcYqmIzqpsjjiua/YwVNA88BbmkXj76JI7bfZV+/q8BWNYQVEJRIt0q24EB6jvhx5ciQtIAAwYTaXQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
